package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"time"

	"github.com/conq/backend/api-gateway/graph/generated"
	"github.com/conq/backend/api-gateway/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	// Call the auth service via gRPC
	resp, err := r.AuthClient.Register(ctx, input.Email, input.Password, input.Name)
	if err != nil {
		return nil, fmt.Errorf("failed to register user: %w", err)
	}

	// Check if registration was successful
	if !resp.Success {
		return nil, fmt.Errorf("registration failed: %s", resp.Message)
	}

	// Convert protobuf User to GraphQL User model
	var user *model.User
	if resp.User != nil {
		user = &model.User{
			ID:        resp.User.Id,
			Name:      resp.User.Name,
			Email:     resp.User.Email,
			Role:      &resp.User.Role,
			CreatedAt: time.Unix(resp.User.CreatedAt, 0),
			UpdatedAt: time.Unix(resp.User.UpdatedAt, 0),
		}
	}

	// Return the GraphQL response
	return &model.AuthResponse{
		Token:        resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		User:         user,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	// Call the auth service via gRPC
	resp, err := r.AuthClient.Login(ctx, input.Email, input.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to login: %w", err)
	}

	// Check if login was successful
	if !resp.Success {
		return nil, fmt.Errorf("login failed: %s", resp.Message)
	}

	// Convert protobuf User to GraphQL User model
	var user *model.User
	if resp.User != nil {
		user = &model.User{
			ID:        resp.User.Id,
			Name:      resp.User.Name,
			Email:     resp.User.Email,
			Role:      &resp.User.Role,
			CreatedAt: time.Unix(resp.User.CreatedAt, 0),
			UpdatedAt: time.Unix(resp.User.UpdatedAt, 0),
		}
	}

	// Return the GraphQL response
	return &model.AuthResponse{
		Token:        resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		User:         user,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, input model.ForgotPasswordInput) (bool, error) {
	panic(fmt.Errorf("not implemented: ForgotPassword - forgotPassword"))
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.ResetPasswordInput) (bool, error) {
	panic(fmt.Errorf("not implemented: ResetPassword - resetPassword"))
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (bool, error) {
	panic(fmt.Errorf("not implemented: ChangePassword - changePassword"))
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (bool, error) {
	panic(fmt.Errorf("not implemented: VerifyEmail - verifyEmail"))
}

// ResendVerification is the resolver for the resendVerification field.
func (r *mutationResolver) ResendVerification(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: ResendVerification - resendVerification"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// ValidateToken is the resolver for the validateToken field.
func (r *queryResolver) ValidateToken(ctx context.Context, token string) (*model.TokenValidationResponse, error) {
	// Call the auth service via gRPC
	resp, err := r.AuthClient.ValidateToken(ctx, token)
	if err != nil {
		return nil, fmt.Errorf("failed to validate token: %w", err)
	}

	// Create the response
	response := &model.TokenValidationResponse{
		Valid: resp.Valid,
	}

	// Set message if provided
	if resp.Message != "" {
		response.Message = &resp.Message
	}

	// If token is valid and we have a user ID, we could fetch user details
	// For now, we'll just return the validation status
	// In a full implementation, you might want to fetch user details from the auth service

	return response, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	// Simple health check - returns OK if the API gateway is running
	// In a full implementation, you might want to check connectivity to downstream services
	return "OK", nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
